# Generated by Django 5.0.6 on 2025-03-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_commentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='Model',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='name',
        ),
    ]
